import importlib as _importlib

imported_modules = {}

class Importer:
    def __init__(self, s, *subs):
        self.s=s
        self.subs=subs
    def module(self):
        return _importlib.import_module(self.s)
    def __getattr__(self, a):
        if self.s in imported_modules:
            mod=imported_modules[self.s]
        else:
            mod = self.module()
            imported_modules[self.s]=mod
            for sub in self.subs:
                if isinstance(sub, str):
                    attr=sub
                    sub=('.'.join((self.s, attr)),)
                else:
                    attr=sub[0]
                    sub=('.'.join((self.s, attr)),)+sub[1:]
                setattr(mod,attr,Importer(*sub))
        return getattr(mod,a)
    def __dir__(self):
        return dir(self.module())
    def __repr__(self):
        args = [repr(self.s)]+[repr(sub) for sub in self.subs]
        return f'{type(self).__name__}({"".join(args)})'

def module_names():
    names = list(imported_modules)
    names.sort()
    return names

def autos():
    return ('\n'.join([f'import {s}' for s in module_names()]))

# 3.5
re=Importer('re')
difflib=Importer('difflib')
textwrap=Importer('textwrap')
unicodedata=Importer('unicodedata')
stringprep=Importer('stringprep')
readline=Importer('readline')
rlcompleter=Importer('rlcompleter')
struct=Importer('struct')
codecs=Importer('codecs')
datetime=Importer('datetime')
calendar=Importer('calendar')
collections=Importer('collections','abc')
heapq=Importer('heapq')
bisect=Importer('bisect')
array=Importer('array')
weakref=Importer('weakref')
types=Importer('types')
copy=Importer('copy')
pprint=Importer('pprint')
reprlib=Importer('reprlib')
enum=Importer('enum')
numbers=Importer('numbers')
math=Importer('math')
cmath=Importer('cmath')
decimal=Importer('decimal')
fractions=Importer('fractions')
random=Importer('random')
statistics=Importer('statistics')
itertools=Importer('itertools')
functools=Importer('functools')
operator=Importer('operator')
pathlib=Importer('pathlib')
fileinput=Importer('fileinput')
stat=Importer('stat')
filecmp=Importer('filecmp')
tempfile=Importer('tempfile')
glob=Importer('glob')
fnmatch=Importer('fnmatch')
linecache=Importer('linecache')
shutil=Importer('shutil')
macpath=Importer('macpath')
pickle=Importer('pickle')
copyreg=Importer('copyreg')
shelve=Importer('shelve')
marshal=Importer('marshal')
dbm=Importer('dbm')
sqlite3=Importer('sqlite3')
zlib=Importer('zlib')
gzip=Importer('gzip')
bz2=Importer('bz2')
lzma=Importer('lzma')
zipfile=Importer('zipfile')
tarfile=Importer('tarfile')
csv=Importer('csv')
configparser=Importer('configparser')
netrc=Importer('netrc')
xdrlib=Importer('xdrlib')
plistlib=Importer('plistlib')
hashlib=Importer('hashlib')
hmac=Importer('hmac')
os=Importer('os','path')
io=Importer('io')
time=Importer('time')
argparse=Importer('argparse')
getopt=Importer('getopt')
logging=Importer('logging','config','handlers')
getpass=Importer('getpass')
curses=Importer('curses','textpad','ascii','panel')
platform=Importer('platform')
errno=Importer('errno')
ctypes=Importer('ctypes')
threading=Importer('threading')
multiprocessing=Importer('multiprocessing')
concurrent=Importer('concurrent','futures')
subprocess=Importer('subprocess')
sched=Importer('sched')
queue=Importer('queue')
dummy_threading=Importer('dummy_threading')
_thread=Importer('_thread')
_dummy_thread=Importer('_dummy_thread')
socket=Importer('socket')
ssl=Importer('ssl')
select=Importer('select')
selectors=Importer('selectors')
asyncio=Importer('asyncio')
asyncore=Importer('asyncore')
asynchat=Importer('asynchat')
signal=Importer('signal')
mmap=Importer('mmap')
email=Importer('email', 'charset', 'contentmanager', 'encoders', 'errors', 'generator', 'header', 'headerregistry', 'iterators', 'message', 'mime', 'parser', 'policy', 'utils')
json=Importer('json')
mailcap=Importer('mailcap')
mailbox=Importer('mailbox')
mimetypes=Importer('mimetypes')
base64=Importer('base64')
binhex=Importer('binhex')
binascii=Importer('binascii')
quopri=Importer('quopri')
uu=Importer('uu')
html=Importer('html','parser','entities')
xml=Importer('xml',('etree','ElementTree'),('dom','minidom','pulldom'),('sax','handler','saxutils','xmlreader'),('parsers','expat'))
webbrowser=Importer('webbrowser')
cgi=Importer('cgi')
cgitb=Importer('cgitb')
wsgiref=Importer('wsgiref')
urllib=Importer('urllib','request','response','parse','error','robotparser')
http=Importer('http','client')
ftplib=Importer('ftplib')
poplib=Importer('poplib')
imaplib=Importer('imaplib')
nntplib=Importer('nntplib')
smtplib=Importer('smtplib')
smtpd=Importer('smtpd')
telnetlib=Importer('telnetlib')
uuid=Importer('uuid')
socketserver=Importer('socketserver')
http=Importer('http','server','cookies','cookiejar')
xmlrpc=Importer('xmlrpc','client','server')
ipaddress=Importer('ipaddress')
audioop=Importer('audioop')
aifc=Importer('aifc')
sunau=Importer('sunau')
wave=Importer('wave')
chunk=Importer('chunk')
colorsys=Importer('colorsys')
imghdr=Importer('imghdr')
sndhdr=Importer('sndhdr')
ossaudiodev=Importer('ossaudiodev')
gettext=Importer('gettext')
locale=Importer('locale')
turtle=Importer('turtle')
cmd=Importer('cmd')
shlex=Importer('shlex')
tkinter=Importer('tkinter','ttk','tix','scrolledtext')
IDLE=Importer('IDLE')
Other=Importer('Other')
typing=Importer('typing')
pydoc=Importer('pydoc')
doctest=Importer('doctest')
unittest=Importer('unittest','mock')
## 2to3=Importer('2to3')
test=Importer('test','support')
bdb=Importer('bdb')
faulthandler=Importer('faulthandler')
pdb=Importer('pdb')
The=Importer('The')
timeit=Importer('timeit')
trace=Importer('trace')
tracemalloc=Importer('tracemalloc')
distutils=Importer('distutils')
ensurepip=Importer('ensurepip')
venv=Importer('venv')
zipapp=Importer('zipapp')
sys=Importer('sys')
sysconfig=Importer('sysconfig')
builtins=Importer('builtins')
warnings=Importer('warnings')
contextlib=Importer('contextlib')
abc=Importer('abc')
atexit=Importer('atexit')
traceback=Importer('traceback')
gc=Importer('gc')
inspect=Importer('inspect')
site=Importer('site')
fpectl=Importer('fpectl')
code=Importer('code')
codeop=Importer('codeop')
zipimport=Importer('zipimport')
pkgutil=Importer('pkgutil')
modulefinder=Importer('modulefinder')
runpy=Importer('runpy')
importlib=Importer('importlib','resources')
parser=Importer('parser')
ast=Importer('ast')
symtable=Importer('symtable')
symbol=Importer('symbol')
token=Importer('token')
keyword=Importer('keyword')
tokenize=Importer('tokenize')
tabnanny=Importer('tabnanny')
pyclbr=Importer('pyclbr')
py_compile=Importer('py_compile')
compileall=Importer('compileall')
dis=Importer('dis')
pickletools=Importer('pickletools')
formatter=Importer('formatter')
msilib=Importer('msilib')
msvcrt=Importer('msvcrt')
winreg=Importer('winreg')
winsound=Importer('winsound')
posix=Importer('posix')
pwd=Importer('pwd')
spwd=Importer('spwd')
grp=Importer('grp')
crypt=Importer('crypt')
termios=Importer('termios')
tty=Importer('tty')
pty=Importer('pty')
fcntl=Importer('fcntl')
pipes=Importer('pipes')
resource=Importer('resource')
nis=Importer('nis')
syslog=Importer('syslog')
optparse=Importer('optparse')
imp=Importer('imp')
ntpath=Importer('ntpath')
posixpath=Importer('posixpath')
secrets=Importer('secrets')
contextvars=Importer('contextvars')
dataclasses=Importer('dataclasses')

